/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ListPagination {
        /**
          * The count of all items in the list.
         */
        "count": number;
        /**
          * How many items per page shall be shown on the list?
         */
        "itemsPerPage": number;
        /**
          * The current offset of the list.
         */
        "offset": number;
    }
    interface PokemonList {
        /**
          * The title of this Pokémon List.
         */
        "listTitle": string;
    }
}
declare global {
    interface HTMLListPaginationElement extends Components.ListPagination, HTMLStencilElement {
    }
    var HTMLListPaginationElement: {
        prototype: HTMLListPaginationElement;
        new (): HTMLListPaginationElement;
    };
    interface HTMLPokemonListElement extends Components.PokemonList, HTMLStencilElement {
    }
    var HTMLPokemonListElement: {
        prototype: HTMLPokemonListElement;
        new (): HTMLPokemonListElement;
    };
    interface HTMLElementTagNameMap {
        "list-pagination": HTMLListPaginationElement;
        "pokemon-list": HTMLPokemonListElement;
    }
}
declare namespace LocalJSX {
    interface ListPagination {
        /**
          * The count of all items in the list.
         */
        "count"?: number;
        /**
          * How many items per page shall be shown on the list?
         */
        "itemsPerPage"?: number;
        /**
          * The current offset of the list.
         */
        "offset"?: number;
        /**
          * Emits, when a paging is triggered.
         */
        "onPaging"?: (event: CustomEvent<{ offset: number }>) => void;
    }
    interface PokemonList {
        /**
          * The title of this Pokémon List.
         */
        "listTitle"?: string;
    }
    interface IntrinsicElements {
        "list-pagination": ListPagination;
        "pokemon-list": PokemonList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "list-pagination": LocalJSX.ListPagination & JSXBase.HTMLAttributes<HTMLListPaginationElement>;
            "pokemon-list": LocalJSX.PokemonList & JSXBase.HTMLAttributes<HTMLPokemonListElement>;
        }
    }
}
